### ISSUE TITLE
PokemonAuditSimulator - Failure to Remove Allowances on Blacklisted Addresses Leads to Loss of Funds

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-unitasprotocol-judging#12]
PokemonAuditSimulator

medium

# Failure to Remove Allowances on Blacklisted Addresses Leads to Loss of Funds

## Summary
If you give allowance to a user and he turns malicious and gets blacklisted, because `notBlacklisted(spender)` you are not able to decrease it. If in the future he gets whitelisted and being able to spend tokens, he would be able to drain you.

## Vulnerability Detail
So you have granted some approvals on tokens to some users, but one of them turn malicious, and before you could call [`decreaseAllowance()`](https://github.com/sherlock-audit/2023-04-unitasprotocol/blob/main/Unitas-Protocol/src/ERC20Token.sol#L241-L250), the governance blacklist them. Now if you try to remove the allowance (because the user is malicious) you are not gonna be able to due to:
```jsx
function decreaseAllowance(address spender, uint256 subtractedValue) public whenNotPaused notBlacklisted(msg.sender) 
```

The allowance stays, and if one day the user gets removed from the blacklist ([`removeBlackList()`](https://github.com/sherlock-audit/2023-04-unitasprotocol/blob/main/Unitas-Protocol/src/ERC20Token.sol#L272-L275C6)), he would still have the previous allowance that you gave him. Thus he would be able to use your tokens for malicious stuff again.

```jsx
    function decreaseAllowance(address spender, uint256 subtractedValue) public whenNotPaused notBlacklisted(msg.sender) notBlacklisted(spender) override returns (bool) {
        address owner = _msgSender();
        uint256 currentAllowance = allowance(owner, spender);
        require(currentAllowance >= subtractedValue, "ERC20: decreased allowance below zero");
        unchecked {
            _approve(owner, spender, currentAllowance - subtractedValue);
        }

        return true;
    }
```
## Impact
User lose funds, because they are not able to remove approvals on blacklisted addresses.
## Tool used

Manual Review

## Recommendation
remove the blacklist modifier from `decreaseAllowance()`

**Comment by 0x3b33** [comment]
Escalate for 10 USDC
I want to escalate it on the fact that the protocol has `addBlackList()` and `removeBlackList()` meaning they will be able to blacklist and whitelist users. And if a user gets blacklisted all of the allowance that you gave them with approve will be stuck until he is whitelisted again.This is because of  `notBlacklisted(spender)`. 
```jsx 
    function decreaseAllowance(address spender, uint256 subtractedValue) public whenNotPaused notBlacklisted(msg.sender) notBlacklisted(spender) override returns (bool) {
```
    
Also I think you should be able to decrease the allowance even if blacklisted users. They are not gonna be able to use it if they are currently blacklisted and `decreaseAllowance()` is only lowering it.

If you are not able to do this (like now) when the users can back-run the TX for whitelisting and use your allowance, before you have the chance to remove it.

**Comment by ctf-sec** [comment]
valid low

**Comment by 0x3b33** [comment]
I think it's a med since it pretty much resembles the ERC20 approve sandwich attack in a way. The main user has no control over approvals. Like in the ERC20 approve sandwich the attacker can front-run the user by spending his allowance before the approval, here also the attacker can back-run the system by spending the approval right after the whitelist.

**Comment by DevABDee** [comment]
I agree with the lead judge, It's a valid low and should be fixed. 

Users should not give allowance to anybody they don't trust. I don't remember the protocol but I think it was Uniswap, who didn't fix the sandwich approval issue because of the same reason. It's a user mistake issue, which Sherlock doesn't count as a valid finding. But again I think this should be fixed.

**Comment by jacksanford1** [comment]
Yes, seems like an unfortunate functionality that should likely be fixed, but it does not result in a material loss of funds except for a user who already made a decision to give allowance to the blacklisted user. And that decision is a user error, not an exploit.

**Comment by hrishibhat** [comment]
Result:
Low
Unique

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [PokemonAuditSimulator](https://github.com/sherlock-audit/2023-04-unitasprotocol-judging/issues/12/#issuecomment-1603648306): rejected

**Comment by jacksanford1** [comment]
Result:
Low
Unique
