### ISSUE TITLE
dirk_y - Lack of oracle timestamp validation could result in stale or permanently manipulated prices

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-unitasprotocol-judging#30]
dirk_y

high

# Lack of oracle timestamp validation could result in stale or permanently manipulated prices

## Summary
It is possible for the oracle feeder to call `putPrice` with any timestamp value greater than the previous timestamp. A bug or exploit in the off-chain oracle feeder could update one/many asset prices to an arbitrarily high timestamp (worst case of `type(uint64).max`). At this point further price updates with proper timestamps will fail and the price of the asset will be stale, leading to permanent loss.

## Vulnerability Detail
When updating the price for an asset, the oracle feeder only has to ensure that the new timestamp is greater than the previous timestamp:

```solidity
require(prev_timestamp < timestamp, "Outdated timestamp");
```

Since we cannot trust off-chain code or the APIs that the off-chain code relies on, we shouldn't assume that the timestamp submitted is always going to be valid. Due to a bug in the off-chain code, or due to some off-chain exploit, the oracle feeder could feasibly update the timestamp to any value greater than the previous timestamp, up to `type(uint64).max`.

The important distinction between this vulnerability vs just being able to set an arbitrary price, is that setting an arbitrary timestamp can be permanent and non-recoverable, and also the protocol has a min/max price tolerance safety check built in.

## Impact
The worst case scenario is that off-chain code is exploited, and the malicious actor updates the price to a price tolerance extreme (either high or low depending on the asset) whilst also setting the timestamp to `type(uint64).max`. At this point there is no way to recover the price to the correct value and the asset price is permanently manipulated.

Another scenario is that the off-chain code has a bug and the timestamp is accidentally miscalculated and inflated. At this point, further price updates will fail until the proper timestamp becomes greater than the last miscalculated timestamp. Price calculations rely on calls to `getLatestPrice`, so the price returned by this method will be stale. Alternatively the oracle feeder could artificially inflate the timestamp to recover from this error, however the timestamp would then be incorrect going forwards and would impact any front-ends or other dependent protocols relying on the timestamp of calls to `getPrice`.

## Code Snippet
https://github.com/sherlock-audit/2023-04-unitasprotocol/blob/main/Unitas-Protocol/src/XOracle.sol#L26-L32

## Tool used
Manual Review

## Recommendation
There should be a sanity check for the timestamp argument in `putPrice`. I would recommend adding some tolerance to account for transaction delays:

```solidity
require(timestamp < block.timestamp + TIMESTAMP_TOLERANCE && timestamp > block.timestamp - TIMESTAMP_TOLERANCE, "Timestamp out of range");
```

where `TIMESTAMP_TOLERANCE` is a constant with a permitted block timestamp range e.g. 100.

**Comment by djb15** [comment]
Escalate for 10 USDC
I'm still trying to understand exactly where the line is for admin input validation, however my understanding is there should be input validation if an incorrect admin input is:
1. Non-recoverable
2. Could result in a loss of funds

For the issue detailed in this report both of the above are true. The loss of funds would come from the token price being (potentially permanently) incorrect and exchange rates being miscalculated; one party will win, the other party will lose. Having looked at some other reports (like https://github.com/sherlock-audit/2022-10-mycelium-judging-new/issues/164) I think I've wrongly misclassified this as "high" though; it should instead be "medium".

**Comment by ctf-sec** [comment]
the timestamp value is admin input validation, oracle feeder is in charge of the putting the right timestamp and price, invalid

**Comment by jacksanford1** [comment]
@djb15 Any response to ctf-sec's comment?

I agree the docs are not as clear as they could be on this. We'll clarify it. But if this is a loss of funds caused by an incorrect admin input, it should not be valid. 

putPrice() is controlled by the Feeder role, which is an EOA. Effectively an admin. And admins are trusted in this protocol according to the README. So while you're correct that something (hack or bug) could go wrong off-chain, Sherlock's mandate according to the README is to assume that the off-chain values are correct. If we continued down the path of assuming every off-chain value is malicious, the number of checks needed would likely be untenably large.

**Comment by djb15** [comment]
I'm happy for this issue to be considered invalid as I understand the reasoning. However the documentation probably needs to remove the reference to https://github.com/sherlock-audit/2022-10-mycelium-judging-new/issues/164 as a valid issue then? It's not clear to me how these are different as that one is also a loss of funds/functionality due to an incorrect admin input. I think that issue sets a precedent where admin input validation can be valid but it sounds like maybe admin input validation should just be "low" across the board (or the valid edge cases needs to be much more clearly defined)?

**Comment by jacksanford1** [comment]
@djb15 You're correct about https://github.com/sherlock-audit/2022-10-mycelium-judging-new/issues/164 being a mistake and it will be removed from the documentation. Thanks for flagging this and apologies for the inconvenience. Incorrect admin inputs should be low across the board and this will be made clear in the documentation very soon.

**Comment by jacksanford1** [comment]
Result:
Low
Unique

**Comment by hrishibhat** [comment]
Result:
Low
Unique

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [djb15](https://github.com/sherlock-audit/2023-04-unitasprotocol-judging/issues/30/#issuecomment-1603603422): accepted
