### ISSUE TITLE
Ruhum - Updating USD1 address will leave existing users & protocol with worthless tokens

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-unitasprotocol-judging#58]
Ruhum

medium

# Updating USD1 address will leave existing users & protocol with worthless tokens

## Summary
The protocol allows the admin to update the USD1 address. That will render the token worthless because it can't be traded for the underlying asset anymore. It also deletes the existing USD1 tokens from the protocol's liabilities leaving it with a higher reserve ratio than it should.

## Vulnerability Detail
Through the timelock, the admin is able to update the address of USD1:

```sol
    function setUSD1(address token) external onlyTimelock {
        _setUSD1(token);
    }

    function _setUSD1(address token) internal {
        address oldToken = address(usd1);
        if (oldToken != address(0)) {
            _removeToken(oldToken);
        }

        _addToken(token, uint8(TokenType.Stable));
        usd1 = IERC20Token(token);
    }

    function _removeToken(address token) internal override {
        _require(pairTokenLength(token) == 0, Errors.PAIRS_MUST_REMOVED);

        super._removeToken(token);

        if (token == address(usd1)) {
            usd1 = IERC20Token(address(0x0));
        }
    }
```

Since the old token is removed, you won't be able to swap it for any of the other tokens through the Unitas contract. That makes the token worthless since its value depends on the underlying asset it's pegged to.

Also, `_getTotalLiabilities()` won't use the old USD1 supply to calculate the contract's liabilities since it's removed from the TokenManager:

```sol
    function _getTotalLiabilities() internal view returns (uint256 liabilities) {
        address baseToken = address(tokenManager.usd1());
        uint8 tokenTypeValue = uint8(ITokenManager.TokenType.Stable);
        uint256 tokenCount = tokenManager.tokenLength(tokenTypeValue);
        uint256 priceBase = 10 ** oracle.decimals();

        for (uint256 i; i < tokenCount; i++) {
            address token = tokenManager.tokenByIndex(tokenTypeValue, i);
            uint256 tokenSupply = IERC20Token(token).totalSupply();

            if (token == baseToken) {
                // Adds up directly when the token is USD1
                liabilities += tokenSupply;
            } else if (tokenSupply > 0) {
                uint256 price = oracle.getLatestPrice(token);

                liabilities += _convert(
                    token,
                    baseToken,
                    tokenSupply,
                    MathUpgradeable.Rounding.Down,
                    price,
                    priceBase,
                    token
                );
            }
        }
    }
```

The USDT used to mint the old USD1 tokens still exists inside the Unitas contract.

## Impact
By switching USD1 tokens you:
1. leave existing USD1 holders with a worthless token
2. bump up the Unitas contract's reserve ratio because you delete the existing USD1 supply from the liabilities calculation

## Code Snippet
https://github.com/sherlock-audit/2023-04-unitasprotocol/blob/main/Unitas-Protocol/src/TokenManager.sol#L96
https://github.com/sherlock-audit/2023-04-unitasprotocol/blob/main/Unitas-Protocol/src/TokenManager.sol#L223
https://github.com/sherlock-audit/2023-04-unitasprotocol/blob/main/Unitas-Protocol/src/TokenManager.sol#L265
https://github.com/sherlock-audit/2023-04-unitasprotocol/blob/main/Unitas-Protocol/src/Unitas.sol#L540
## Tool used

Manual Review

## Recommendation
Switching USD1 should only be allowed if the existing supply of the old token is 0, or if existing USD1 holders are allowed to migrate to the new token in 1:1 ratio.

**Comment by 0xruhum** [comment]
Escalate for 10 USDC
This should be a valid issue. While it resembles the traditional configuration issues that are excluded by Sherlock, it's not the same thing.
A configuration issue is when a function has a parameter `x` where some values are valid and others are not. In that case, wardens argued that the function should limit the possible values of the parameter to only allow the valid ones. Sherlock deems these issues invalid. See https://docs.sherlock.xyz/audits/judging/judging#list-of-issue-categories-that-are-not-considered-valid

But, this submission describes how changing the USD1 address after launch can break the whole system. It doesn't matter what kind of value you call the function with. Changing the USD1 address will remove existing liabilities (old USD1) from the system. It's not part of the original configuration either since that's done in the constructor of the contract: https://github.com/sherlock-audit/2023-04-unitasprotocol/blob/main/Unitas-Protocol/src/TokenManager.sol#L88

This specific function will be used to change the address after launch. By including the function the protocol devs show that they think it might be necessary at some point. No matter what value you use, changing the USD1 address will cause issues as described in the original submission. It shouldn't be possible to change the address unless you can guarantee that there is no existing holder of the old USD1 token, i.e. `totalSupply() == 0`. Since that's not possible, you should remove the function altogether. Calling it will do more harm than good.

**Comment by ctf-sec** [comment]
Will bring this for sponsor review, intend to mark as valid low

**Comment by jacksanford1** [comment]
Because this issue requires an admin to willfully take a bad action to cause a loss of funds, it cannot be valid. It is an interesting point that any action an admin could take (with respect to calling this function) would be a bad action. 

Maybe @Adityaxrex or others will have a comment on why this function exists, but either way it cannot be a valid issue because it requires an admin to cause the loss of funds, and admins are trusted in this protocol.

**Comment by 0xruhum** [comment]
My argument here is that the existence of the function shows that the admin might not have been fully aware of the damage that changing the USD1 address would do. I assume it was added to allow upgrading the USD1 token's functionality at some point in the future.

But, as described in the submission, changing the USD1 address will break the protocol and cause lost funds for existing users. USD1 only has value if it can be swapped back to the underlying collateral (USDT). By changing the address of USD1 to xUSD1, all the holders of USD1 are left with a worthless token because they aren't able to swap back to USDT.

**Comment by jacksanford1** [comment]
Result:
Low
Unique

**Comment by hrishibhat** [comment]
Result:
Low
Unique

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xruhum](https://github.com/sherlock-audit/2023-04-unitasprotocol-judging/issues/58/#issuecomment-1603235580): rejected
